apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: openperouter
allowHostDirVolumePlugin: true
allowHostNetwork: true
allowPrivilegedContainer: true
fsGroup:
  type: RunAsAny
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
seLinuxContext: 
  type: RunAsAny
users:
  - system:serviceaccount:openperouter-system:openperouter-perouter
  - system:serviceaccount:openperouter-system:openperouter-pecontroller
volumes:
- '*'

