apiVersion: k8s.ovn.org/v1
kind: EgressIP
metadata:
  name: egressips-prod
spec:
  egressIPs:
  - 192.169.10.6
  namespaceSelector:
    matchLabels:
      app: test
---
apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: egressip
  namespace: metallb-system
spec:
  bgp:
    routers:
    - asn: 64515
      neighbors:
      - address: 192.169.10.1
        holdTime: 1m30s
        keepaliveTime: 30s
        asn: 64512
        toAdvertise:
          allowed:
            mode: all
      prefixes:
      - 192.169.10.6/24


