apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: receiveroutes
  namespace: metallb-system
spec:
  bgp:
    routers:
    - asn: 64515
      neighbors:
      - address: 192.169.10.1
        asn: 64512
        holdTime: 1m30s
        keepaliveTime: 30s
        toReceive:
          allowed:
            mode: all
    - asn: 64515
      neighbors:
      - address: 192.169.11.1
        asn: 64513
        holdTime: 1m30s
        keepaliveTime: 30s
        toReceive:
          allowed:
            mode: all
