apiVersion: v1
kind: Namespace
metadata:
  name: green
  labels:
    app: green
---
apiVersion: v1
kind: Pod
metadata:
  name: agnhost
  namespace: green
  labels:
    app: green
spec:
  containers:
  - args:
    - netexec
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    name: agnhost
    ports:
    - name: http
      containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: testsvc
  namespace: green
spec:
  ports:
  - name: http
    port: 82
    protocol: TCP
    targetPort: 8080
  selector:
    app: green
  type: LoadBalancer
---
apiVersion: v1
kind: Namespace
metadata:
  name: red
  labels:
    app: red
---
apiVersion: v1
kind: Pod
metadata:
  name: agnhost
  namespace: red
  labels:
    app: red
spec:
  containers:
  - args:
    - netexec
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    name: agnhost
    ports:
    - name: http
      containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: testsvc
  namespace: red
spec:
  ports:
  - name: http
    port: 82
    protocol: TCP
    targetPort: 8080
  selector:
    app: red
  type: LoadBalancer
