apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    app: test
---
apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: test
spec:
  containers:
    - name: client
      image: praqma/network-multitool:latest
      command: ["/bin/sh", "-c"]
      args:
        ["sleep INF"]
